learning_templates/basicapp/urls.py
from django.urls import path
from basicapp import views

app_name = 'basicapp'

urlpatterns = [
    path('relative/',views.relative,name='relative'),
    path('other/',views.other,name='other'),

]

learning_templates/learning_templates/urls.py
from django.contrib import admin
from django.urls import path,include
from basicapp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name='index'),
    path('basicapp/',include('basicapp.urls')),


]

learning_templates/basicapp/models.py
from django.db import models

# Create your models here.

learning_templates/basicapp/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    condic = {'text':'hello world', 'number': 100}
    return render(request, 'basicapp/index.html', context=condic)

def other(request):
    return render(request, 'basicapp/other.html')

def relative(request):
    return render(request,'basicapp/relative_url.html')

learning_templates/templates/basicapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

</head>
<body>
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <ul class="nav navbar-nav">
                <li><a href="{% url 'index' %}" class="navbar-brand">BRAND</a></li>
                <li><a href="{% url 'admin:index' %}" class="navbar-link">ADMIN</a></li>
                <li><a href="{% url 'basicapp:other' %}" class="navbar-link">OTHER</a></li>
            </ul>
        </div>
    </nav>
    <div class="container">

        {% block body_block %}
            <h1>KEK</h1>
        {% endblock %}
    </div>
</body>
</html>

learning_templates/templates/basicapp/index.html
<!DOCTYPE html>

{% extends "basicapp/base.html" %}
{% block body_block %}
{% load my_extras %}
    <h1>welcome to index</h1>
    <h1>
        {{ text | curt:'hello' }} 
    </h1>
    <h1>
        {{ number|add:'99' }}
    </h1>
    
    {% endblock %}

learning_templates/templates/basicapp/other.html
<!DOCTYPE html>
{% extends "basicapp/base.html" %}
{% block body_block %}
    <h1>welcome to other</h1>
    <h2>inheritance!</h2>
{% endblock %}

learning_templates/templates/basicapp/relative_url.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>welcome to relative</h1>
    <a href="{% url 'basicapp:other' %}">the other page</a>
    <a href="{% url 'admin:index' %}">AAAAAAAAD</a>
    <a href="{% url 'index' %}">IND</a>
</body>
</html>